version: '3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smart-brain
    ports:
      - "5432:5432"
    volumes:
      - "./setup-db.sql:/docker-entrypoint-initdb.d/init.sql"
  # app:
  #   image: my-node-app
  #   ports:
  #     - "3000:3000"